name: Snyk Security

on:
  push:
  pull_request:
  schedule:
    - cron: "17 3 * * 1"

permissions:
  contents: read

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Snyk security scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --severity-threshold=high